<?php
 $phpCodeSnifferConfig = array (
  'installed_paths' => 'C:\\Users\\Sandeep\\AppData\\Local\\Temp\\phpcs-standards\\WordPress-Coding-Standards-3.1.0,C:\\Users\\Sandeep\\AppData\\Local\\Temp\\phpcs-standards\\PHPCSUtils-1.0.12,C:\\Users\\Sandeep\\AppData\\Local\\Temp\\phpcs-standards\\PHPCSExtra-1.2.1',
);
?>